# Generated by Django 6.0.1 on 2026-01-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_review_text_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
